version: "3.1"
services:
  php-postgres:
    image: postgres:11-alpine
#    container_name: php-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
    ports:
      - 5434:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  todo-web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - .:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - todo-php
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  todo-php:
    build: .
    links:
      - php-postgres
    volumes:
      - .:/code
    environment:
      SERVER.HOST: 127.0.0.1
      SERVER.PORT: 8081
      PG.USER: actix
      PG.PASSWORD: actix
      PG.HOST: php-postgres
      PG.PORT: 5432
      PG.DBNAME: actix
      PG.POOL.MAX_SIZE: 30
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'